export const airports = [
  {
    "id": "3240615",
    "gmt": "-10",
    "airport_id": "1",
    "iata_code": "AAA",
    "city_iata_code": "AAA",
    "icao_code": "NTGA",
    "country_iso2": "PF",
    "geoname_id": "6947726",
    "latitude": "-17.05",
    "longitude": "-145.41667",
    "airport_name": "Anaa",
    "country_name": "French Polynesia",
    "phone_number": null,
    "timezone": "Pacific/Tahiti"
  },
  {
    "id": "3240616",
    "gmt": "10",
    "airport_id": "2",
    "iata_code": "AAB",
    "city_iata_code": "AAB",
    "icao_code": "YARY",
    "country_iso2": "AU",
    "geoname_id": "7730796",
    "latitude": "-26.7",
    "longitude": "141.04167",
    "airport_name": "Arrabury",
    "country_name": "Australia",
    "phone_number": null,
    "timezone": "Australia/Brisbane"
  },
  {
    "id": "3240617",
    "gmt": "2",
    "airport_id": "3",
    "iata_code": "AAC",
    "city_iata_code": "AAC",
    "icao_code": "HEAR",
    "country_iso2": "EG",
    "geoname_id": "6297289",
    "latitude": "31.133333",
    "longitude": "33.75",
    "airport_name": "El Arish International Airport",
    "country_name": "Egypt",
    "phone_number": null,
    "timezone": "Africa/Cairo"
  },
  {
    "id": "3240618",
    "gmt": "1",
    "airport_id": "4",
    "iata_code": "AAE",
    "city_iata_code": "AAE",
    "icao_code": "DABB",
    "country_iso2": "DZ",
    "geoname_id": "2570559",
    "latitude": "36.821392",
    "longitude": "7.811857",
    "airport_name": "Les Salines",
    "country_name": null,
    "phone_number": null,
    "timezone": "Africa/Algiers"
  },
  {
    "id": "3240619",
    "gmt": "-5",
    "airport_id": "5",
    "iata_code": "AAF",
    "city_iata_code": "AAF",
    "icao_code": "KAAF",
    "country_iso2": "US",
    "geoname_id": "4146153",
    "latitude": "29.733334",
    "longitude": "-84.98333",
    "airport_name": "Apalachicola Regional",
    "country_name": "United States",
    "phone_number": null,
    "timezone": "America/New_York"
  },
  {
    "id": "3240620",
    "gmt": "-3",
    "airport_id": "6",
    "iata_code": "AAG",
    "city_iata_code": "AAG",
    "icao_code": "SSYA",
    "country_iso2": "BR",
    "geoname_id": "3471795",
    "latitude": "-24.103611",
    "longitude": "-49.79",
    "airport_name": "Arapoti",
    "country_name": "Brazil",
    "phone_number": null,
    "timezone": "America/Sao_Paulo"
  },
  {
    "id": "3240621",
    "gmt": "1",
    "airport_id": "7",
    "iata_code": "AAH",
    "city_iata_code": "AAH",
    "icao_code": "EDKA",
    "country_iso2": "DE",
    "geoname_id": "3207669",
    "latitude": "50.75",
    "longitude": "6.133333",
    "airport_name": "Aachen/Merzbruck",
    "country_name": "Germany",
    "phone_number": null,
    "timezone": "Europe/Berlin"
  },
  {
    "id": "3240622",
    "gmt": "-3",
    "airport_id": "8",
    "iata_code": "AAI",
    "city_iata_code": "AAI",
    "icao_code": "SWRA",
    "country_iso2": "BR",
    "geoname_id": "7668483",
    "latitude": "-12.916667",
    "longitude": "-46.933334",
    "airport_name": "Arraias",
    "country_name": "Brazil",
    "phone_number": null,
    "timezone": "America/Araguaina"
  },
  {
    "id": "3240624",
    "gmt": "12",
    "airport_id": "10",
    "iata_code": "AAK",
    "city_iata_code": "AAK",
    "icao_code": "NGUK",
    "country_iso2": "KI",
    "geoname_id": "7521791",
    "latitude": "0.166667",
    "longitude": "173.58333",
    "airport_name": "Aranuka",
    "country_name": "Kiribati",
    "phone_number": null,
    "timezone": "Pacific/Tarawa"
  },
  {
    "id": "3240625",
    "gmt": "1",
    "airport_id": "11",
    "iata_code": "AAL",
    "city_iata_code": "AAL",
    "icao_code": "EKYT",
    "country_iso2": "DK",
    "geoname_id": "2624887",
    "latitude": "57.08655",
    "longitude": "9.872241",
    "airport_name": "Aalborg",
    "country_name": "Denmark",
    "phone_number": null,
    "timezone": "Europe/Copenhagen"
  },
  {
    "id": "3240626",
    "gmt": "2",
    "airport_id": "12",
    "iata_code": "AAM",
    "city_iata_code": "AAM",
    "icao_code": "FAMD",
    "country_iso2": "ZA",
    "geoname_id": "7668229",
    "latitude": "-24.8",
    "longitude": "31.533333",
    "airport_name": "Mala Mala",
    "country_name": "South Africa",
    "phone_number": null,
    "timezone": "Africa/Johannesburg"
  },
  {
    "id": "3240627",
    "gmt": "4",
    "airport_id": "13",
    "iata_code": "AAN",
    "city_iata_code": "AAN",
    "icao_code": "OMAL",
    "country_iso2": "AE",
    "geoname_id": "6300095",
    "latitude": "24.260231",
    "longitude": "55.616627",
    "airport_name": "Al Ain",
    "country_name": "United Arab Emirates",
    "phone_number": null,
    "timezone": "Asia/Dubai"
  },
  {
    "id": "3240629",
    "gmt": "3",
    "airport_id": "15",
    "iata_code": "AAQ",
    "city_iata_code": "AAQ",
    "icao_code": "URKA",
    "country_iso2": "RU",
    "geoname_id": "6300989",
    "latitude": "44.9",
    "longitude": "37.316666",
    "airport_name": "Anapa",
    "country_name": "Russia",
    "phone_number": null,
    "timezone": "Europe/Moscow"
  },
  {
    "id": "3240630",
    "gmt": "1",
    "airport_id": "16",
    "iata_code": "AAR",
    "city_iata_code": "AAR",
    "icao_code": "EKAH",
    "country_iso2": "DK",
    "geoname_id": "2611665",
    "latitude": "56.30823",
    "longitude": "10.626351",
    "airport_name": "Aarhus Airport",
    "country_name": "Denmark",
    "phone_number": null,
    "timezone": "Europe/Copenhagen"
  },
  {
    "id": "3240632",
    "gmt": "8",
    "airport_id": "18",
    "iata_code": "AAT",
    "city_iata_code": "AAT",
    "icao_code": "ZWAT",
    "country_iso2": "CN",
    "geoname_id": "7910421",
    "latitude": "47.750362",
    "longitude": "88.08444",
    "airport_name": "Altay",
    "country_name": "China",
    "phone_number": null,
    "timezone": "Asia/Shanghai"
  },
  {
    "id": "3240636",
    "gmt": "-3",
    "airport_id": "22",
    "iata_code": "AAX",
    "city_iata_code": "AAX",
    "icao_code": "SBAX",
    "country_iso2": "BR",
    "geoname_id": "7668431",
    "latitude": "-19.568056",
    "longitude": "-46.92917",
    "airport_name": "Araxa",
    "country_name": "Brazil",
    "phone_number": null,
    "timezone": "America/Sao_Paulo"
  },
  {
    "id": "3240637",
    "gmt": "3",
    "airport_id": "23",
    "iata_code": "AAY",
    "city_iata_code": "AAY",
    "icao_code": "OYGD",
    "country_iso2": "YE",
    "geoname_id": "7668412",
    "latitude": "16.19596",
    "longitude": "52.173256",
    "airport_name": "Al Ghaydah",
    "country_name": "Yemen",
    "phone_number": null,
    "timezone": "Asia/Aden"
  },
  {
    "id": "3240638",
    "gmt": "-6",
    "airport_id": "24",
    "iata_code": "AAZ",
    "city_iata_code": "AAZ",
    "icao_code": "MGQZ",
    "country_iso2": "GT",
    "geoname_id": "6299804",
    "latitude": "14.87",
    "longitude": "-91.5",
    "airport_name": "Quetzaltenango",
    "country_name": "Guatemala",
    "phone_number": null,
    "timezone": "America/Guatemala"
  },
  {
    "id": "3240639",
    "gmt": "7",
    "airport_id": "25",
    "iata_code": "ABA",
    "city_iata_code": "ABA",
    "icao_code": "UNAA",
    "country_iso2": "RU",
    "geoname_id": "6300982",
    "latitude": "53.716667",
    "longitude": "91.5",
    "airport_name": "Abakan",
    "country_name": "Russia",
    "phone_number": null,
    "timezone": "Asia/Krasnoyarsk"
  },
  {
    "id": "3240640",
    "gmt": "1",
    "airport_id": "26",
    "iata_code": "ABB",
    "city_iata_code": "ABB",
    "icao_code": "DNAS",
    "country_iso2": "NG",
    "geoname_id": "7668214",
    "latitude": "6.203333",
    "longitude": "6.65888",
    "airport_name": "Asaba International",
    "country_name": "Nigeria",
    "phone_number": null,
    "timezone": "Africa/Lagos"
  },
  {
    "id": "3240641",
    "gmt": "1",
    "airport_id": "27",
    "iata_code": "ABC",
    "city_iata_code": "ABC",
    "icao_code": "LEAB",
    "country_iso2": "ES",
    "geoname_id": "6299323",
    "latitude": "38.948334",
    "longitude": "-1.863333",
    "airport_name": "Los Llanos",
    "country_name": "Spain",
    "phone_number": null,
    "timezone": "Europe/Madrid"
  },
];

export const countries = [
  {
    "id": "77869",
    "capital": "Andorra la Vella",
    "currency_code": "EUR",
    "fips_code": "AN",
    "country_iso2": "AD",
    "country_iso3": "AND",
    "continent": "EU",
    "country_id": "1",
    "country_name": "Andorra",
    "currency_name": "Euro",
    "country_iso_numeric": "20",
    "phone_prefix": "376",
    "population": "84000"
  },
  {
    "id": "77870",
    "capital": "Abu Dhabi",
    "currency_code": "AED",
    "fips_code": "AE",
    "country_iso2": "AE",
    "country_iso3": "ARE",
    "continent": "AS",
    "country_id": "2",
    "country_name": "United Arab Emirates",
    "currency_name": "Dirham",
    "country_iso_numeric": "784",
    "phone_prefix": "971",
    "population": "4975593"
  },
  {
    "id": "77871",
    "capital": "Kabul",
    "currency_code": "AFN",
    "fips_code": "AF",
    "country_iso2": "AF",
    "country_iso3": "AFG",
    "continent": "AS",
    "country_id": "3",
    "country_name": "Afghanistan",
    "currency_name": "Afghani",
    "country_iso_numeric": "4",
    "phone_prefix": "93",
    "population": "29121286"
  },
  {
    "id": "77872",
    "capital": "St. John's",
    "currency_code": "XCD",
    "fips_code": "AC",
    "country_iso2": "AG",
    "country_iso3": "ATG",
    "continent": "NA",
    "country_id": "4",
    "country_name": "Antigua and Barbuda",
    "currency_name": "Dollar",
    "country_iso_numeric": "28",
    "phone_prefix": "+1-268",
    "population": "86754"
  },
  {
    "id": "77873",
    "capital": "The Valley",
    "currency_code": "XCD",
    "fips_code": "AV",
    "country_iso2": "AI",
    "country_iso3": "AIA",
    "continent": "NA",
    "country_id": "5",
    "country_name": "Anguilla",
    "currency_name": "Dollar",
    "country_iso_numeric": "660",
    "phone_prefix": "+1-264",
    "population": "13254"
  },
  {
    "id": "77874",
    "capital": "Tirana",
    "currency_code": "ALL",
    "fips_code": "AL",
    "country_iso2": "AL",
    "country_iso3": "ALB",
    "continent": "EU",
    "country_id": "6",
    "country_name": "Albania",
    "currency_name": "Lek",
    "country_iso_numeric": "8",
    "phone_prefix": "355",
    "population": "2986952"
  },
  {
    "id": "77875",
    "capital": "Yerevan",
    "currency_code": "AMD",
    "fips_code": "AM",
    "country_iso2": "AM",
    "country_iso3": "ARM",
    "continent": "AS",
    "country_id": "7",
    "country_name": "Armenia",
    "currency_name": "Dram",
    "country_iso_numeric": "51",
    "phone_prefix": "374",
    "population": "2968000"
  },
  {
    "id": "77876",
    "capital": "Willemstad",
    "currency_code": "ANG",
    "fips_code": "NT",
    "country_iso2": "AN",
    "country_iso3": "ANT",
    "continent": "NA",
    "country_id": "8",
    "country_name": "Netherlands Antilles",
    "currency_name": "Guilder",
    "country_iso_numeric": "530",
    "phone_prefix": "599",
    "population": "136197"
  },
  {
    "id": "77877",
    "capital": "Luanda",
    "currency_code": "AOA",
    "fips_code": "AO",
    "country_iso2": "AO",
    "country_iso3": "AGO",
    "continent": "AF",
    "country_id": "9",
    "country_name": "Angola",
    "currency_name": "Kwanza",
    "country_iso_numeric": "24",
    "phone_prefix": "244",
    "population": "13068161"
  },
  {
    "id": "77878",
    "capital": null,
    "currency_code": null,
    "fips_code": "AY",
    "country_iso2": "AQ",
    "country_iso3": "ATA",
    "continent": "AN",
    "country_id": "10",
    "country_name": "Antarctica",
    "currency_name": null,
    "country_iso_numeric": "10",
    "phone_prefix": null,
    "population": null
  },
  {
    "id": "77879",
    "capital": "Buenos Aires",
    "currency_code": "ARS",
    "fips_code": "AR",
    "country_iso2": "AR",
    "country_iso3": "ARG",
    "continent": "SA",
    "country_id": "11",
    "country_name": "Argentina",
    "currency_name": "Peso",
    "country_iso_numeric": "32",
    "phone_prefix": "54",
    "population": "41343201"
  },
  {
    "id": "77880",
    "capital": "Pago Pago",
    "currency_code": "USD",
    "fips_code": "AQ",
    "country_iso2": "AS",
    "country_iso3": "ASM",
    "continent": "OC",
    "country_id": "12",
    "country_name": "American Samoa",
    "currency_name": "Dollar",
    "country_iso_numeric": "16",
    "phone_prefix": "+1-684",
    "population": "57881"
  },
  {
    "id": "77881",
    "capital": "Vienna",
    "currency_code": "EUR",
    "fips_code": "AU",
    "country_iso2": "AT",
    "country_iso3": "AUT",
    "continent": "EU",
    "country_id": "13",
    "country_name": "Austria",
    "currency_name": "Euro",
    "country_iso_numeric": "40",
    "phone_prefix": "43",
    "population": "8205000"
  },
  {
    "id": "77882",
    "capital": "Canberra",
    "currency_code": "AUD",
    "fips_code": "AS",
    "country_iso2": "AU",
    "country_iso3": "AUS",
    "continent": "OC",
    "country_id": "14",
    "country_name": "Australia",
    "currency_name": "Dollar",
    "country_iso_numeric": "36",
    "phone_prefix": "61",
    "population": "21515754"
  },
  {
    "id": "77883",
    "capital": "Oranjestad",
    "currency_code": "AWG",
    "fips_code": "AA",
    "country_iso2": "AW",
    "country_iso3": "ABW",
    "continent": "NA",
    "country_id": "15",
    "country_name": "Aruba",
    "currency_name": "Guilder",
    "country_iso_numeric": "533",
    "phone_prefix": "297",
    "population": "71566"
  },
  {
    "id": "77884",
    "capital": "Mariehamn",
    "currency_code": "EUR",
    "fips_code": null,
    "country_iso2": "AX",
    "country_iso3": "ALA",
    "continent": "EU",
    "country_id": "16",
    "country_name": "Aland Islands",
    "currency_name": "Euro",
    "country_iso_numeric": "248",
    "phone_prefix": "+358-18",
    "population": "26711"
  },
  {
    "id": "77885",
    "capital": "Baku",
    "currency_code": "AZN",
    "fips_code": "AJ",
    "country_iso2": "AZ",
    "country_iso3": "AZE",
    "continent": "AS",
    "country_id": "17",
    "country_name": "Azerbaijan",
    "currency_name": "Manat",
    "country_iso_numeric": "31",
    "phone_prefix": "994",
    "population": "8303512"
  },
  {
    "id": "77886",
    "capital": "Sarajevo",
    "currency_code": "BAM",
    "fips_code": "BK",
    "country_iso2": "BA",
    "country_iso3": "BIH",
    "continent": "EU",
    "country_id": "18",
    "country_name": "Bosnia and Herzegovina",
    "currency_name": "Marka",
    "country_iso_numeric": "70",
    "phone_prefix": "387",
    "population": "4590000"
  },
  {
    "id": "77887",
    "capital": "Bridgetown",
    "currency_code": "BBD",
    "fips_code": "BB",
    "country_iso2": "BB",
    "country_iso3": "BRB",
    "continent": "NA",
    "country_id": "19",
    "country_name": "Barbados",
    "currency_name": "Dollar",
    "country_iso_numeric": "52",
    "phone_prefix": "+1-246",
    "population": "285653"
  },
  {
    "id": "77888",
    "capital": "Dhaka",
    "currency_code": "BDT",
    "fips_code": "BG",
    "country_iso2": "BD",
    "country_iso3": "BGD",
    "continent": "AS",
    "country_id": "20",
    "country_name": "Bangladesh",
    "currency_name": "Taka",
    "country_iso_numeric": "50",
    "phone_prefix": "880",
    "population": "156118464"
  },
  {
    "id": "77889",
    "capital": "Brussels",
    "currency_code": "EUR",
    "fips_code": "BE",
    "country_iso2": "BE",
    "country_iso3": "BEL",
    "continent": "EU",
    "country_id": "21",
    "country_name": "Belgium",
    "currency_name": "Euro",
    "country_iso_numeric": "56",
    "phone_prefix": "32",
    "population": "10403000"
  }
]